### ISSUE TITLE
project id was string instead of integer

### ISSUE THREAD

**Issue by ygerasimov** [DiffyWebsite/wordpress-diffy#7]
[Fri Mar 12 02:12:40.751718 2021] [php7:error] [pid 49] [client ] PHP Fatal error: Uncaught TypeError: Argument 1 passed to Diffy\\Project::get() must be of the type int, string given, called in /var/www/html/site/public_html/wp-content/plugins/diffy/admin/class-wordpress-diffy-admin.php on line 267 and defined in /var/www/html/site/public_html/wp-content/plugins/diffy/vendor/diffywebsite/diffy-php/src/Project.php:71\nStack trace:\n#0 /var/www/html/site/public_html/wp-content/plugins/diffy/admin/class-wordpress-diffy-admin.php(267): Diffy\\Project::get('Thatsmarketing')\n#1 /var/www/html/site/public_html/wp-includes/class-wp-hook.php(289): Diffy_Admin->diffy_validate_project_id_callback('Thatsmarketing')\n#2 /var/www/html/site/public_html/wp-includes/plugin.php(212): WP_Hook->apply_filters('Thatsmarketing', Array)\n#3 /var/www/html/site/public_html/wp-includes/formatting.php(4906): apply_filters('sanitize_option...', 'Thatsmarketing', 'diffy_project_i...', 'Thatsmarketing')\n#4 /var/www/html/site/public_html/wp-includes/option.php(369): sanitize_option('diffy_project_i...', 'Thatsmarketing')\n#5 /va in /var/www/html/site/public_html/wp-content/plugins/diffy/vendor/diffywebsite/diffy-php/src/Project.php on line 71, referer: https://beta-thatsmarketing.e.wpstage.net/wp-admin/admin.php?page=wordpress-diffy

**Comment by gregurco** [comment]
Fixed in #9
